# Generated by Django 6.0.1 on 2026-01-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_completos', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=10)),
                ('paralelo', models.CharField(max_length=5)),
                ('horas_semanales', models.IntegerField(default=5)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=10)),
                ('paralelo', models.CharField(max_length=5)),
                ('jornada', models.CharField(max_length=20)),
                ('anio_lectivo', models.CharField(max_length=9)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('GRADUADO', 'Graduado'), ('RETIRADO', 'Retirado')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'anio_lectivo')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo'), (3, 'Tercero')])),
                ('leccion1', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('leccion2', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('actividad_experiencial', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('promedio_formativo', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('aporte_formativo_70', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('proyecto_interdisciplinar', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('examen', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('promedio_sumativo', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('aporte_sumativo_30', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('promedio_final_100', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.estudiante')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.matricula')),
            ],
            options={
                'unique_together': {('estudiante', 'asignatura', 'trimestre')},
            },
        ),
    ]
