# Generated by Django 6.0 on 2026-01-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='matricula',
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['estudiante', 'asignatura', 'trimestre']},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombres_completos']},
        ),
        migrations.RemoveField(
            model_name='docente',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='anio_lectivo',
            field=models.CharField(blank=True, help_text='Ejemplo: 2024-2025', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(blank=True, choices=[('5EGB', '5.º de EGB'), ('6EGB', '6.º de EGB'), ('7EGB', '7.º de EGB'), ('8EGB', '8.º de EGB'), ('9EGB', '9.º de EGB'), ('10EGB', '10.º de EGB'), ('1BGU', '1.º de BGU'), ('2BGU', '2.º de BGU'), ('3BGU', '3.º de BGU')], max_length=10),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='jornada',
            field=models.CharField(blank=True, choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna'), ('INTEGRAL', 'Integral')], max_length=15),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('EGB_MEDIA', '🔹 EGB Media'), ('EGB_SUPERIOR', '🔹 EGB Superior'), ('BGU', '🔹 Bachillerato')], max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='paralelo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='grado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(choices=[('LENGUA', 'Lengua y Literatura'), ('MATEMATICA', 'Matemática'), ('CIENCIAS', 'Ciencias Naturales'), ('SOCIALES', 'Estudios Sociales'), ('ARTISTICA', 'Educación Cultural y Artística'), ('FISICA', 'Educación Física'), ('INGLES', 'Lengua Extranjera (Inglés)'), ('COMPUTACION', 'Computación'), ('EMPRENDIMIENTO', 'Emprendimiento y Gestión'), ('PROYECTO', 'Proyecto Escolar'), ('ETICA', 'Ética y Valores'), ('CIUDADANIA', 'Participación Ciudadana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='paralelo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='actividad_experiencial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Actividad Experiencial (0-10)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='aporte_formativo_70',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='aporte_sumativo_30',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='examen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Examen (0-10)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='leccion1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Lección 1 (0-10)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='leccion2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Lección 2 (0-10)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio_final_100',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio_formativo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio_sumativo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='proyecto_interdisciplinar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Proyecto Interdisciplinar (0-10)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='trimestre',
            field=models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')]),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
