# Generated by Django 6.0 on 2026-01-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_remove_calificacion_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'ordering': ['estudiante', 'asignatura', 'trimestre'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombres_completos'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='nivel_educativo',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='paralelo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='nivel_educativo',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.docente', verbose_name='Docente'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='horas_semanales',
            field=models.IntegerField(default=5, verbose_name='Horas Semanales'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(choices=[('LENGUA', 'Lengua y Literatura'), ('MATEMATICA', 'Matemática'), ('CIENCIAS', 'Ciencias Naturales'), ('SOCIALES', 'Estudios Sociales'), ('ARTISTICA', 'Educación Cultural y Artística'), ('FISICA', 'Educación Física'), ('INGLES', 'Lengua Extranjera (Inglés)'), ('COMPUTACION', 'Computación'), ('EMPRENDIMIENTO', 'Emprendimiento y Gestión')], max_length=100, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='aporte_formativo_70',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Aporte Formativo (70%)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='aporte_sumativo_30',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Aporte Sumativo (30%)'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio_final_100',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Promedio Final'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio_formativo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Promedio Formativo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='promedio_sumativo',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Promedio Sumativo'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='trimestre',
            field=models.IntegerField(choices=[(1, 'Primer Trimestre'), (2, 'Segundo Trimestre'), (3, 'Tercer Trimestre')], verbose_name='Trimestre'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombres_completos',
            field=models.CharField(max_length=200, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='anio_lectivo',
            field=models.CharField(help_text='Ejemplo: 2024-2025', max_length=20, verbose_name='Año lectivo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.CharField(choices=[('5EGB', '5.º de EGB'), ('6EGB', '6.º de EGB'), ('7EGB', '7.º de EGB'), ('8EGB', '8.º de EGB'), ('9EGB', '9.º de EGB'), ('10EGB', '10.º de EGB'), ('1BGU', '1.º de BGU'), ('2BGU', '2.º de BGU'), ('3BGU', '3.º de BGU')], max_length=10, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='jornada',
            field=models.CharField(choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna')], max_length=15, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_nacimiento',
            field=models.CharField(max_length=100, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres_completos',
            field=models.CharField(max_length=200, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='paralelo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Paralelo'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
