# Generated by Django 4.2.7 on 2026-01-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('tipo', models.CharField(choices=[('COMPUTADORA', 'Computadora'), ('LAPTOP', 'Laptop'), ('IMPRESORA', 'Impresora'), ('PROYECTOR', 'Proyector'), ('TABLET', 'Tablet'), ('SERVER', 'Servidor'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('MONITOR', 'Monitor'), ('TELEVISOR', 'Televisor')], max_length=50, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('anio_adquisicion', models.IntegerField(verbose_name='Año de Adquisición')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DAÑADO', 'Dañado'), ('BAJA', 'Dado de Baja')], max_length=20, verbose_name='Estado')),
                ('condicion_fisica', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, verbose_name='Condición Física')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo_inventario'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('aula_laboratorio', models.CharField(max_length=100, verbose_name='Aula/Laboratorio')),
                ('piso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso')),
                ('edificio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edificio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['area', 'aula_laboratorio'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo'), ('CALIBRACION', 'Calibración')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('actividades_realizadas', models.TextField(verbose_name='Actividades Realizadas')),
                ('repuestos', models.TextField(blank=True, null=True, verbose_name='Repuestos Utilizados')),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Mantenimiento')),
                ('estado_posterior', models.CharField(max_length=50, verbose_name='Estado Posterior')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
            },
        ),
    ]
