# Generated by Django 6.0.1 on 2026-01-23 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitucionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=200)),
                ('codigo_amie', models.CharField(max_length=20, unique=True)),
                ('provincia', models.CharField(max_length=50)),
                ('canton', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('tipo_institucion', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('FISCOMISIONAL', 'Fiscomisional'), ('MUNICIPAL', 'Municipal')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaBarreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_encuesta', models.DateField()),
                ('encuestador', models.CharField(max_length=200)),
                ('cargo_encuestador', models.CharField(max_length=100)),
                ('p1_accesos', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p2_pasillos', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p3_rampas', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p4_ascensores', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p5_banos', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p6_puertas', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p7_senialetica', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p8_equipos', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p9_internet', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p10_software', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p11_plataformas', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p12_capacitacion', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p13_soporte', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('p14_recursos', models.CharField(choices=[('SIEMPRE', 'Siempre (80-100%)'), ('CASI_SIEMPRE', 'Casi Siempre (60-79%)'), ('AVECES', 'A veces (40-59%)'), ('CASI_NUNCA', 'Casi Nunca (20-39%)'), ('NUNCA', 'Nunca (0-19%)'), ('NO_APLICA', 'No aplica')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesibilidad.institucioneducativa')),
            ],
            options={
                'unique_together': {('institucion', 'fecha_encuesta')},
            },
        ),
    ]
