# Generated by Django 5.1 on 2026-01-23 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesibilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestabarreras',
            options={'ordering': ['-fecha_encuesta'], 'verbose_name': 'Encuesta de Barreras', 'verbose_name_plural': 'Encuestas de Barreras'},
        ),
        migrations.AlterModelOptions(
            name='institucioneducativa',
            options={'ordering': ['nombre_institucion'], 'verbose_name': 'Institución Educativa', 'verbose_name_plural': 'Instituciones Educativas'},
        ),
        migrations.AlterUniqueTogether(
            name='encuestabarreras',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='encuestabarreras',
            name='p4_banos',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='4. Los baños son accesibles'),
        ),
        migrations.AddField(
            model_name='encuestabarreras',
            name='p5_puertas',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='5. Las puertas tienen ancho adecuado'),
        ),
        migrations.AddField(
            model_name='encuestabarreras',
            name='p6_senialetica',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='6. La señalética es adecuada'),
        ),
        migrations.AddField(
            model_name='encuestabarreras',
            name='p7_iluminacion',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='7. La iluminación es adecuada'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='cargo_encuestador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Encuestador'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='encuestador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Encuestador'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='fecha_encuesta',
            field=models.DateField(verbose_name='Fecha de Encuesta'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accesibilidad.institucioneducativa', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p10_software',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='10. Se dispone de software educativo accesible'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p11_plataformas',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='11. Las plataformas virtuales son accesibles'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p12_capacitacion',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='12. Hay capacitación regular en tecnología'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p13_soporte',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='13. Existe soporte técnico adecuado'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p14_recursos',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='14. Los recursos digitales son accesibles'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p1_accesos',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='1. Los accesos principales al edificio son fáciles de usar'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p2_pasillos',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='2. Los pasillos y aulas están libres de obstáculos'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p3_rampas',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='3. Existen rampas de acceso adecuadas'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p8_equipos',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='8. La institución cuenta con equipos tecnológicos suficientes'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='p9_internet',
            field=models.CharField(choices=[('SIEMPRE', 'Siempre'), ('CASI_SIEMPRE', 'Casi Siempre'), ('AVECES', 'A veces'), ('CASI_NUNCA', 'Casi Nunca'), ('NUNCA', 'Nunca'), ('NO_APLICA', 'No aplica')], default='NO_APLICA', max_length=20, verbose_name='9. La conexión a internet es estable'),
        ),
        migrations.AlterField(
            model_name='encuestabarreras',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='canton',
            field=models.CharField(max_length=50, verbose_name='Cantón'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='codigo_amie',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código AMIE'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='nombre_institucion',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='provincia',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='institucioneducativa',
            name='tipo_institucion',
            field=models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('FISCOMISIONAL', 'Fiscomisional'), ('MUNICIPAL', 'Municipal')], max_length=20, verbose_name='Tipo de Institución'),
        ),
        migrations.RemoveField(
            model_name='encuestabarreras',
            name='p4_ascensores',
        ),
        migrations.RemoveField(
            model_name='encuestabarreras',
            name='p5_banos',
        ),
        migrations.RemoveField(
            model_name='encuestabarreras',
            name='p6_puertas',
        ),
        migrations.RemoveField(
            model_name='encuestabarreras',
            name='p7_senialetica',
        ),
    ]
